version: '3'
services:
  app:
    container_name: api
    build: .
    ports: 
      - 8000:8000
    restart: on-failure
    environment:
      - MONGO_HOSTNAME=mongo
    depends_on:
      - mongo
    networks:
      - default

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/var/lib/mongo/data
    networks:
      - default

volumes:
  dbdata:

networks:
  default:
